//eventEmitter
export const INITAUDIO = 'INITAUDIO';
export const INITLOCALAUDIO = 'INITLOCALAUDIO';
export const SNACKBAROPEN = 'SNACKBAROPEN';
export const SWITCHPLAY = 'SWITCHPLAY';
export const PLAYPERCENT = 'PLAYPERCENT';

//redux
export const SET_RECOMMEND_LIST = 'SET_RECOMMEND_LIST';
export const SET_NEWEST_LIST = 'SET_NEWEST_LIST';
export const SET_ALBUM_LIST = 'SET_ALBUM_LIST';
export const SET_CURRENTSONG_INFO = 'SET_CURRENTSONG_INFO';
export const SET_PLAY_UI_PAGE = 'SET_PLAY_UI_PAGE';
export const SET_SONG_INFO = 'SET_SONG_INFO';
export const SET_PLAY_STATE = 'SET_PLAY_STATE';