//eventEmitter
export const INITAUDIO = 'INITAUDIO';
export const INITLOCALAUDIO = 'INITLOCALAUDIO';
export const SNACKBAROPEN = 'SNACKBAROPEN';
export const SWITCHPLAY = 'SWITCHPLAY';
export const PLAYPERCENT = 'PLAYPERCENT';
export const OPENFILEDIALOG = 'OPENFILEDIALOG';
export const BARLOADING = 'BARLOADING';
export const PLAYANIMATE = 'PLAYANIMATE';
export const SONGLOADING = 'SONGLOADING';
export const CLOSEWINDOW = 'CLOSEWINDOW';
export const MINWINDOW = 'MINWINDOW';
export const RINGLOADING = 'RINGLOADING';
export const SWITCHORDER = 'SWITCHORDER';
export const UPDATETIMEPERCENT = 'UPDATETIMEPERCENT';
export const NEXT = 'NEXT';
export const CREATESHUFFLE = 'CREATESHUFFLE';
export const BATCHADD = 'BATCHADD';

//redux
export const SET_RECOMMEND_LIST = 'SET_RECOMMEND_LIST';
export const SET_NEWEST_LIST = 'SET_NEWEST_LIST';
export const SET_ALBUM_LIST = 'SET_ALBUM_LIST';
export const SET_CURRENTSONG_INFO = 'SET_CURRENTSONG_INFO';
export const SET_PLAY_UI_PAGE = 'SET_PLAY_UI_PAGE';
export const SET_SONG_INFO = 'SET_SONG_INFO';
export const SET_PLAY_STATE = 'SET_PLAY_STATE';
export const SET_VOLUME = 'SET_VOLUME';
export const SET_PLAYORDER = 'SET_PLAYORDER';
export const SET_PLAYLIST = 'SET_PLAYLIST';
export const SET_SHUFFLELIST = 'SET_SHUFFLELIST';
export const SET_LOCALPLAYLIST = 'SET_LOCALPLAYLIST';